---
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['host.docker.internal:9090']

  - job_name: 'api'
    metrics_path: '/metrics'
    scrape_interval: 15s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          group: 'production'
